name: Deploy Environments
run-name: " API_ENV: ${{ inputs.branch }} | Deploy Environments "

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Api Gateway Stage'
        type: choice
        default: dev1
        required: true
        options:
          - dev1
          - dev2
          - dev3
  # push:
  #   branches:
  #     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          ls -al
          cd projectApi
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset